/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      // 设计 Token → Tailwind 主题（唯一配色来源见 src/styles/tokens.css）
      colors: {
        brown: 'var(--brown)',
        'brown-d': 'var(--brown-d)',
        cream: 'var(--cream)',
        olive: 'var(--olive)',
        orange: 'var(--orange)',
        night: 'var(--night)',
        ink: 'var(--ink)',
        'ink-2': 'var(--ink-2)',
        'ink-3': 'var(--ink-3)',
        card: 'var(--card)',
        line: 'var(--line)',
        ring: 'var(--ring)',
        'c-transport': 'var(--c-transport)',
        'c-hotel': 'var(--c-hotel)',
        'c-food': 'var(--c-food)',
        'c-ticket': 'var(--c-ticket)',
        'c-shop': 'var(--c-shop)',
        'c-other': 'var(--c-other)',
      },
      fontSize: {
        display: ['22px', { lineHeight: '1.3', fontWeight: '700' }],
        brand: ['19px', { lineHeight: '1.2', fontWeight: '800' }],
        title: ['16px', { lineHeight: '1.4', fontWeight: '700' }],
        heading: ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        subheading: ['13.5px', { lineHeight: '1.4', fontWeight: '600' }],
        body: ['14px', { lineHeight: '1.5' }],
        'body-sm': ['13px', { lineHeight: '1.5' }],
        caption: ['12.5px', { lineHeight: '1.4' }],
        hint: ['11px', { lineHeight: '1.3' }],
        micro: ['10.5px', { lineHeight: '1.3', fontWeight: '500' }],
        number: ['22px', { lineHeight: '1', fontWeight: '800' }],
        'number-md': ['20px', { lineHeight: '1', fontWeight: '700' }],
        'number-sm': ['15px', { lineHeight: '1', fontWeight: '700' }],
      },
      borderRadius: {
        'r-xs': '6px',
        'r-sm': '9px',
        'r-md': '12px',
        'r-lg': '14px',
        'r-xl': '16px',
        'r-2xl': '18px',
        'r-sheet': '22px',
        'r-full': '999px',
      },
      boxShadow: {
        'e-1': '0 6px 20px rgba(90,66,40,.08)',
        'e-2': '0 8px 20px rgba(139,94,60,.3)',
        'e-3': '0 12px 26px rgba(139,94,60,.42)',
        'e-sheet': '0 -10px 30px rgba(60,42,20,.16)',
        'e-frame': '0 30px 80px rgba(60,42,20,.28)',
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
      },
    },
  },
  plugins: [],
}
